name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, json, curl
          coverage: none

      - run: composer install --no-interaction --prefer-dist

      # PHPStan
      - name: Run PHPStan
        run: composer stan

      # PHPUnit
      - name: Run PHPUnit tests
        run: composer test

      # PHP-CS-Fixer check
      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
